# Generated by Django 5.0.3 on 2024-03-08 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='myUser',
        ),
    ]
