# Generated by Django 5.0.3 on 2024-03-09 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_rename_userid_myuser_id_remove_myuser_last_login_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('pregnancy', models.CharField(blank=True, choices=[('T', 'True'), ('F', 'False')], max_length=1, null=True)),
                ('allergies', models.JSONField(blank=True, default=list)),
                ('chronic_illnesses', models.JSONField(blank=True, default=list)),
                ('dietary_preferences', models.JSONField(blank=True, default=list)),
                ('religious_restrictions', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='login.myuser')),
            ],
        ),
    ]
