# Generated by Django 5.0.3 on 2024-03-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='allergies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='myuser',
            name='chronic_illnesses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='myuser',
            name='dietary_preferences',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='myuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='pregnancy',
            field=models.CharField(blank=True, choices=[('T', 'True'), ('F', 'False')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='religious_restrictions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
