# Generated by Django 5.0.3 on 2024-03-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_myuser_allergies_myuser_chronic_illnesses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='religious_restrictions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
