# Generated by Django 5.0.3 on 2024-03-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_myuser_religious_restrictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
