# Generated by Django 5.0.3 on 2024-04-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_myuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='myuser',
            name='shopping_list',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
